### ISSUE TITLE
! LaTeX Error: File `resumecls.cls' not found.

### ISSUE THREAD

**Issue by wingjay** [huxuan/resumecls-example#2]
do you know why?

**Comment by huicpc0215** [comment]
Maybe your Latex is too old. You can update or download from [here](http://www.ctan.org/tex-archive/macros/xetex/latex/resumecls)

**Comment by huxuan** [comment]
@wingjay Just as @huicpc0215 has said, you need to update your local CTAN repo.

**Comment by huxuan** [comment]
Feel free to reopen this issue if you failed to solve it. We are always here for help.
