### ISSUE TITLE
can't expand to 2 pages

### ISSUE THREAD

**Issue by yuhengd** [huxuan/resumecls-example#3]
When I write the resume-zh.tex to be more than 2 pages. It overlaps at the the end of the page and could not display a full 2 page resume in chinese. Thanks!

**Comment by huxuan** [comment]
Please refer to here [1] for details about multiple page support. 

[1] https://github.com/huxuan/resumecls/blob/master/resumecls.dtx#L369

**Comment by huxuan** [comment]
Close as resolved via email.
