### ISSUE TITLE
求助简历添加证件照

### ISSUE THREAD

**Issue by wyk-qyf** [huxuan/resumecls-example#4]
您好，感谢你的简历，我想在模板上添加证件照，请问如何实现？我可以正常编译的。

**Comment by wyk-qyf** [comment]
Hello, thank you for your resume, I would like to add a photo on the template, how to achieve? I can compile it normally.

**Comment by huxuan** [comment]
Hi @wyk-qyf, currently there is no support in resumecls template. You may need to change the resumecls template code to make it.
